### ISSUE TITLE
NameError: name 'namesArr' is not defined

### ISSUE THREAD

**Issue by trockenasche** [ToddShepard/plugin.video.c3#7]
I set the system time to 2014-12-28 21:25 to test the new json version and getting following error:

Error Type: <type 'exceptions.NameError'>
                                            Error Contents: name 'namesArr' is not defined
                                            Traceback (most recent call last):
                                              File "/plugin.video.c3/default.py", line 156, in <module>
                                                namesArr.append(person['full_public_name'])
                                            NameError: name 'namesArr' is not defined

**Comment by ToddShepard** [comment]
namesArr was not defined, should work now.
